@startuml
title Memory Match Class Diagram
class UpdateHandler {
checkMatch()
}
class User {
}
class Card {
match
id
back
facedown
facedown()
equals()
turnOver()
}

class SplashScreen{
}
class MenuActivity{
runClassicGame()
runTimedGame()
viewScore()
versusMode()
showHowToPlay()
makeMenuVisable()
onResume()
onMenuPressed()
}
class MemoryGame{
cardList[]
buttonList[]
gameBoard
selection1
selection2
gameTimer
mode
tries
totalTime
finalTime
totalMatches
curDifficulty
readSCores()
addScores()
loadPictures()
initialize()
turnFaceUp()
canAddScores()
startTimer()
}
class ViewScoreboard{
topScores
numTopScores
fileName
difficulty
mode
hiScoreFile
readScore()
getFile()
setTopTextView()
}
class HighScoreArchive <<F,orchid) >> {
}
class HowToPlay {
}

MemoryGame "1" *-- "12,16,24" Card : contains >
MemoryGame "1" *-- "1" UpdateHandler: contains >
User -- MemoryGame: plays >
User -- SplashScreen: views >
User -- MenuActivity: selects game mode >
UpdateHandler -- Card : checks match >
MenuActivity -- MemoryGame : starts >
User -- ViewScoreboard : views >
MemoryGame -- HighScoreArchive : adds score >
ViewScoreboard -- HighScoreArchive : retrieve scores >
User -- HowToPlay : views >

@enduml
