@startuml
title MemoryMatch SSD: Play Classic or Timed Mode

User -> MemoryMatchApp : start
User <-- MemoryMatchApp : main menu
User -> MemoryMatchApp : select game mode
User <-- MemoryMatchApp : list of difficulties
User -> MemoryMatchApp : select difficulty
User <-- MemoryMatchApp : game board
loop until all cards matched
User -> MemoryMatchApp: select first card
User <-- MemoryMatchApp : first card image
User -> MemoryMatchApp : select second card
User <-- MemoryMatchApp : second card image
alt cards match
User <-- MemoryMatchApp : removed cards
else cards do not match
User <-- MemoryMatchApp : turned over cards
end
end
alt score good enough to be saved
User -> MemoryMatchApp : enter initials
MemoryMatchApp -> HighScoreArchive : add current score
MemoryMatchApp <-- HighScoreArchive : score added successfully
end



@enduml
