@startuml
partition Activity1 {
(*)-->Splash
}
partition Activity2 {
Splash --> MainMenu
partition Fragment {
MainMenu --> HowToPlay
HowToPlay --> MainMenu
}
}
partition Activity3 {
MainMenu --> MemoryGame
}
-->(*)
partition Activity4 {
MainMenu --> HighScoreArchive
HighScoreArchive --> MainMenu
}





@enduml